modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License" #mandatory
issueTrackerURL="https://github.com/ToMe25/Botania-Additions/issues"
[[mods]] #mandatory
    modId="botaniaadditions" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Botania Additions" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/botania-additions"
    logoFile="BotaniaAdditionsLogo.png"
    credits="..."
    authors="ToMe25"
    description='''Botania Additions is a Botania addon that adds some stuff that should be in Botania imo, but isn't because Botania is feature frozen.'''
[[dependencies.botaniaadditions]]
    modId="forge"
    mandatory=true
    versionRange="[35.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.botaniaadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.botaniaadditions]]
    modId="botania"
    mandatory=true
    versionRange="[1.11-378,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.botaniaadditions]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-42,)"
    side="BOTH"
[[dependencies.botaniaadditions]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.3-4.0.1.0,)"
    ordering="AFTER"
    side="BOTH"
